---
##Directory server; Backed by FreeIPA
- name: Ensure Directory Server is up and configured
  hosts: dirservers
  vars_files:
    - private/esxi-creds.yml
  roles:
    - esxiguest
    #- dirserver
