---
- name: Enable EPEL Repo
  yum : pkg=epel-release state=latest

- name: Install SELinux python bindings
  yum: pkg=libselinux-python state=latest

# Not neccesary to install docker when installed via docker-py
- name: Install Docker Python Module
  yum : name=python-docker-py state=latest

- name   : Start Docker Service
  service: name=docker state=started

- include: create-users.yml
- include: create-directories.yml
