---
#- include: esxi-prereqs.yml

##Ensure ESXi Guest is up and running
- name: Checking VM Configuration
  vsphere_guest:
    guest: "{{ dirserverName1 }}"
    vcenter_hostname: xanatos
    username: "{{ esxiuser }}"
    password: "{{ esxipass }}"
    state: powered_on
    vm_disk:
        disk1: 
            size_gb: 30
            datastore: VMStore
