---
#Demo setup by ansible docs: http://answersforaws.com/code/netflixoss/asgard/
#If using ec2.py default config, must use playbook with: 
#ansible-playbook -i inventory provision.yml
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
        group: [SSH,Web]
        keypair: KeyPair1
        instance_type: t2.micro
        region: us-east-1
        image: ami-96a818fe #CentOS7; #ami-a8d369c0 RHEL7. ami-146e2a7c is AmazonLinuxAMI
        wait: true
        exact_count: 2
        count_tag:
            Name: Owncloud
        instance_tags:
            Name: Owncloud
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groupname=ec2hosts
      with_items: ec2.instances

    - name: Wait for SSH to be available
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: Repo configurations  #Only for CENTOS 7
  sudo: true
  hosts: ec2hosts
  tasks:
    - name: Enable EPEL Repo
      yum: pkg=epel-release state=latest

- name: AWS CLI
  sudo: True
  hosts: ec2hosts

  tasks:
    - include: tasks/install-awscli.yml

- name: Docker and Owncloud
  sudo: True
  hosts: ec2hosts
  
  tasks:
    - include: tasks/install-dockerowncloud.yml

