---
#If using ec2.py default config, must use playbook with: 
#ansible-playbook -i inventory provision.yml
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
        group: [SSH,Web]
        keypair: KeyPair1
        instance_type: t2.micro
        region: us-east-1
        image:  ami-aed06ac6 #ami-c2a818aa #Centos6 HVM
        wait: true
        exact_count: 1
        count_tag:
            Name: RHEL6
        instance_tags:
            Name: RHEL6
        volumes:
            - device_name: /dev/sda1
              volume_size: 10
              delete_on_termination: true
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groupname=ec2hosts
      with_items: ec2.instances

    - name: Wait for SSH to be available
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

