---
- name: Deploy Docker Container
  docker:
    image: registry
    name : registry
    publish_all_ports: True
    restart_policy: always
    state: started
    ports: "127.0.0.1:5000:5000"
    volumes:
        - "/tmp:/tmp"
    env:
        STORAGE_PATH: "/tmp"
        SETTINGS_FLAVOR: "local"
    docker_api_version: "1.15"
  tags:
    - docker

- name: Check if port 5000 is allowed
  shell: iptables -L | grep -q "Allow http"
  register: check_allow_http
  ignore_errors: yes
  changed_when: no
  always_run: yes

- name: Open port 5000
  command: >
    iptables -A INPUT -p tcp -m tcp --dport 5000
    -m comment --comment "Allow docker registry" -j ACCEPT
  when: check_allow_http.rc != 0
  notify:
    - Save iptables

