---
- name: Ensure Apache is installed
  yum : name=httpd state=latest

- name: Start Apache
  service: name=httpd state=started

- name: Check if port 80 is allowed
  shell: iptables -L | grep -q "Allow http"
  register: check_allow_http
  ignore_errors: yes
  changed_when: no
  always_run: yes

- name: Open port 80
  command: >
    iptables -I INPUT -p tcp -m tcp --dport 80
    -m comment --comment "Allow http" -j ACCEPT
  when: check_allow_http.rc != 0
  notify:
    - Save iptables

